### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Clyde962002** [ES-factory/DigiCombo#3]
When compiling the example sketch 'PhonePatternUnlock' I encountered this error. 

BTW, I compile it on my phone with the ArduinoDroid app.

/sdk/hardware/tools/avr/bin/avr-gcc -no-canonical-prefixes -c -g -x assembler-with-cpp -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10812 -DUSB_VID=null -DUSB_PID=null -DIDE="ArduinoDroid" -DARDUINO_ARCH_AVR -DARDUINO_AVR_DIGISPARK /DigiCombo/usbdrvasm_includer.S -o/librariesBuild/DigiCombo/usbdrvasm_includer.S.o /sdk/hardware/tools/avr/bin/avr-g++ -no-canonical-prefixes -std=gnu++11 -c -g -Os -w -mmcu=attiny85 -DF_CPU=16500000L -DUSB_VID=null -DUSB_PID=null -DARDUINO=10812 -DIDE="ArduinoDroid" -DARDUINO_ARCH_AVR -DARDUINO_AVR_DIGISPARK /build/PhonePatternUnlocker.cpp -o /build/PhonePatternUnlocker.cpp.o /sdk/hardware/tools/avr/bin/avr-gcc -no-canonical-prefixes -Os -Wl,--gc-sections -Wl,-T /sdk/hardware/tools/avr/avr/lib/ldscripts/avr25.x -mmcu=attiny85 -o /build/PhonePatternUnlocker.cpp.elf /librariesBuild/DigiCombo/usbdrvasm_includer.S.o /librariesBuild/DigiCombo/DigiComboC.c.o /librariesBuild/DigiCombo/usbdrv_includer.c.o /librariesBuild/DigiCombo/DigiCombo.cpp.o /build/PhonePatternUnlocker.cpp.o /coreBuild/core.a -L/build -lm /librariesBuild/DigiCombo/usbdrv_includer.c.o: In function `usbInit':
/DigiCombo/usbdrv/usbdrv.c:621: undefined reference to `usbCrc16Append'
/DigiCombo/usbdrv/usbdrv.c:621: undefined reference to `usbCrc16Append'
collect2: error: ld returned 1 exit status
Return code is not 0

**Comment by erfansn** [comment]
It is better for you to try the desktop version of Arduino IDE because it is the official version from the Arduino team and it is normal for there to be a problem with the unofficial software available for Android.
